{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "308b5b5e",
   "metadata": {
    "_cell_guid": "96f1d5f4-d150-4d65-805a-7f0c3c92ccc7",
    "_uuid": "67c3e114-49ed-4fb7-b804-167fea957457",
    "collapsed": false,
    "execution": {
     "iopub.execute_input": "2026-06-20T19:22:06.463636Z",
     "iopub.status.busy": "2026-06-20T19:22:06.463305Z",
     "iopub.status.idle": "2026-06-20T19:22:18.544816Z",
     "shell.execute_reply": "2026-06-20T19:22:18.543615Z"
    },
    "jupyter": {
     "outputs_hidden": false
    },
    "papermill": {
     "duration": 12.089217,
     "end_time": "2026-06-20T19:22:18.547488+00:00",
     "exception": false,
     "start_time": "2026-06-20T19:22:06.458271+00:00",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO: Successfully loaded OpenSpiel environments: 24.\n",
      "[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_amazons\n",
      "[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_backgammon\n",
      "[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_checkers\n",
      "[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_chess\n",
      "[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_clobber\n",
      "[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_coin_game\n",
      "[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_coin_game_arena\n",
      "[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_connect_four\n",
      "[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_dark_hex\n",
      "[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_gin_rummy\n",
      "[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_go\n",
      "[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_goofspiel\n",
      "[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_hearts\n",
      "[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_hex\n",
      "[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_lines_of_action\n",
      "[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_matching_pennies_3p\n",
      "[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_oshi_zumo\n",
      "[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_othello\n",
      "[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_repeated_game\n",
      "[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_tic_tac_toe\n",
      "[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_y\n",
      "[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_universal_poker\n",
      "[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_repeated_poker\n",
      "[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    open_spiel_python_repeated_pokerkit\n",
      "[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO: OpenSpiel games skipped: 1.\n",
      "[kaggle_environments.envs.open_spiel_env.open_spiel_env] INFO:    snake\n"
     ]
    }
   ],
   "source": [
    "\"\"\"\n",
    "================================================================================\n",
    "POKÉMON TCG AI BATTLE CHALLENGE — MEGA LUCARIO ex AGENT v5 (NOTEBOOK)\n",
    "================================================================================\n",
    "\n",
    "Full strategy notebook combining:\n",
    "  1. The complete strategy document\n",
    "  2. Cell-by-cell Kaggle notebook structure (Cells 1–6)\n",
    "  3. Self-contained agent with evaluator\n",
    "  4. Local validation harness\n",
    "\n",
    "To use on Kaggle:\n",
    "  - Create a new notebook in the competition (auto-attaches competition data).\n",
    "  - Copy each CELL (marked below) into a separate notebook cell, in order.\n",
    "  - Paste as Code cells, run sequentially.\n",
    "  - Save Version and submit from the competition's Submit tab.\n",
    "\n",
    "================================================================================\n",
    "SECTION 0: THE MEGA LUCARIO ex STRATEGY — COMPLETE REFERENCE\n",
    "================================================================================\n",
    "\n",
    "COMPETITION CONTEXT\n",
    "  - Kaggle simulation competition on the cabt C engine (libcg.so).\n",
    "  - Two tracks: Simulation (ladder) and Strategy (report).\n",
    "  - Decision interface: agent(obs_dict) -> list[int] of legal option indices.\n",
    "  - No rule reimplementation needed: search the engine and evaluate boards.\n",
    "\n",
    "THE DECK — Mega Lucario ex (mono-Fighting aggressive)\n",
    "  Primary attacker:  Mega Lucario ex (678, 340 HP, Stage 1 from Riolu 333)\n",
    "    - Aura Jab (1F):   130 damage + accelerate 3 Fighting from discard to bench\n",
    "    - Mega Brave (2F): 270 damage, cannot use next turn (cooldown)\n",
    "  Secondary:         Bloodmoon Ursaluna ex (135, Basic, Fighting)\n",
    "  Consistency:       4x Riolu, draw/search Trainers, 15x Fighting Energy\n",
    "  Strategy: 340-HP wall survives and swings again (prize tempo win).\n",
    "\n",
    "AGENT ARCHITECTURE — Determinized Forward Search\n",
    "  1. On MAIN decisions with >=2 options:\n",
    "     a. Determinize hidden info (deck order, prizes, opp deck/hand).\n",
    "     b. For each legal option: search_step, rollout YOUR turn, evaluate leaf.\n",
    "     c. Keep the option with highest evaluate value.\n",
    "  2. Any error -> fall back to a rule-based fast policy.\n",
    "\n",
    "THE EVALUATOR — Prize-Trade Anchored (weight scale = 1000 pts/prize)\n",
    "  PRIZE (1000/prize)           opp_prizes_left - my_prizes_left\n",
    "  KO_THEM (350 x pv)           can I KO the opponent active right now?\n",
    "  KO_ME (480 x pv x 1.4×if_ex) can they KO me next turn?\n",
    "  SURVIVE (up to 240)          my active hp survives their output\n",
    "  ACTIVE_READY (120)           my active can afford an attack\n",
    "  BACKUP (170 x <=2)           benched attackers ready to promote\n",
    "  CONDITIONS (±220/170)        my locked? opp locked?\n",
    "  BENCH_EXPOSURE (-110/ex)     benched ex beyond 1 is a liability\n",
    "  DRAW_ACCESS (45 x <=3)       hold draw/search cards\n",
    "  HAND_SIZE (15 x range)       baseline 3, cap 8\n",
    "  DECKOUT (20)                 late-game deep-grind\n",
    "\n",
    "================================================================================\n",
    "\"\"\"\n",
    "\n",
    "import glob\n",
    "import os\n",
    "import random\n",
    "import dataclasses\n",
    "from collections import Counter\n",
    "\n",
    "try:\n",
    "    import kaggle_environments\n",
    "    KE = os.path.dirname(kaggle_environments.__file__)\n",
    "except Exception:\n",
    "    KE = None\n",
    "\n",
    "DECK = [\n",
    "    333, 333, 333, 333,           # Riolu\n",
    "    678, 678, 678, 678,           # Mega Lucario ex\n",
    "    135, 135, 135,                # Bloodmoon Ursaluna ex\n",
    "    1224, 1224, 1224, 1224,       # Trainer\n",
    "    1192, 1192, 1192, 1192,       # Trainer\n",
    "    1213, 1213, 1213, 1213,       # Trainer\n",
    "    1182, 1182, 1182,             # Trainer\n",
    "    1121, 1121, 1121, 1121,       # Trainer\n",
    "    1125,                          # Master Ball (ACE SPEC)\n",
    "    1119, 1119, 1119, 1119,       # Trainer\n",
    "    1116, 1116, 1116, 1116,       # Trainer\n",
    "    1123, 1123, 1123,             # Trainer\n",
    "    1252, 1252, 1252,             # Trainer\n",
    "    6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6  # Fighting Energy\n",
    "]\n",
    "assert len(DECK) == 60\n",
    "\n",
    "NUMBER, YES, NO, CARD, TOOL_CARD, ENERGY_CARD, ENERGY, PLAY, ATTACH, EVOLVE, \\\n",
    "    ABILITY, DISCARD, RETREAT, ATTACK, END, SKILL, SPECIAL_CONDITION = range(17)\n",
    "\n",
    "STRONG_ATTACK = 110\n",
    "ACTIONS_PER_TURN_CAP = 80\n",
    "CHARGE_TO_BEST = True\n",
    "\n",
    "W_PRIZE = 1000.0\n",
    "W_KO_THEM = 350.0\n",
    "W_KO_ME = 480.0\n",
    "W_SURVIVE = 240.0\n",
    "W_ACTIVE_READY = 120.0\n",
    "W_BACKUP = 170.0\n",
    "W_CONDITIONS_SELF = 220.0\n",
    "W_CONDITIONS_OPP = 170.0\n",
    "W_BENCH_EXPOSURE = 110.0\n",
    "W_DRAW_ACCESS = 45.0\n",
    "W_HAND = 15.0\n",
    "W_DECKOUT = 20.0\n",
    "BIG = 1e9\n",
    "\n",
    "_CARDS = None\n",
    "_ATTACKS = None\n",
    "\n",
    "def _meta():\n",
    "    \"\"\"Load card metadata from the engine.\"\"\"\n",
    "    global _CARDS, _ATTACKS\n",
    "    if _CARDS is None:\n",
    "        _CARDS = {}\n",
    "        _ATTACKS = {}\n",
    "        try:\n",
    "            from cg.api import all_card_data, all_attack\n",
    "            for c in all_card_data():\n",
    "                _CARDS[c.cardId] = c\n",
    "            for a in all_attack():\n",
    "                if a.attackId not in _ATTACKS:\n",
    "                    _ATTACKS[a.attackId] = []\n",
    "                _ATTACKS[a.attackId].append((a.damage or 0, tuple(a.energies or [])))\n",
    "        except Exception:\n",
    "            pass\n",
    "    return _CARDS, _ATTACKS\n",
    "\n",
    "def _prize_value(cid):\n",
    "    \"\"\"Return prize value: 3 if megaEx, 2 if ex, else 1.\"\"\"\n",
    "    C, _ = _meta()\n",
    "    c = C.get(cid)\n",
    "    if c:\n",
    "        if getattr(c, 'megaEx', False):\n",
    "            return 3\n",
    "        if getattr(c, 'ex', False):\n",
    "            return 2\n",
    "    return 1\n",
    "\n",
    "def _is_ex(cid):\n",
    "    \"\"\"Return True if card is ex or megaEx.\"\"\"\n",
    "    C, _ = _meta()\n",
    "    c = C.get(cid)\n",
    "    return bool(c and (getattr(c, 'ex', False) or getattr(c, 'megaEx', False)))\n",
    "\n",
    "def _can_pay(cost, have):\n",
    "    \"\"\"Check if energy list `have` can pay `cost`.\"\"\"\n",
    "    need = Counter(e for e in cost if e != 0)\n",
    "    colorless = sum(1 for e in cost if e == 0)\n",
    "    pool = Counter(have)\n",
    "    for col, k in need.items():\n",
    "        if pool[col] < k:\n",
    "            return False\n",
    "        pool[col] -= k\n",
    "    return sum(pool.values()) >= colorless\n",
    "\n",
    "def _affordable_dmg(pk):\n",
    "    \"\"\"Return best damage this Pokémon can deal with current energy.\"\"\"\n",
    "    if not pk:\n",
    "        return 0\n",
    "    C, A = _meta()\n",
    "    have = pk.get(\"energies\") or []\n",
    "    c = C.get(pk.get(\"id\"))\n",
    "    best = 0\n",
    "    if c:\n",
    "        for aid in getattr(c, 'attacks', []):\n",
    "            if aid in A:\n",
    "                for dmg, cost in A[aid]:\n",
    "                    if _can_pay(cost, have):\n",
    "                        best = max(best, dmg)\n",
    "    return best\n",
    "\n",
    "def _damage_to(att, dfn):\n",
    "    \"\"\"Compute damage from attacker to defender, including Weakness.\"\"\"\n",
    "    if not att or not dfn:\n",
    "        return 0\n",
    "    C, _ = _meta()\n",
    "    d = _affordable_dmg(att)\n",
    "    if d == 0:\n",
    "        return 0\n",
    "    ca = C.get(att.get(\"id\"))\n",
    "    cd = C.get(dfn.get(\"id\"))\n",
    "    if ca and cd:\n",
    "        att_type = getattr(ca, 'energyType', None)\n",
    "        weakness = getattr(cd, 'weakness', None)\n",
    "        if weakness and att_type == weakness:\n",
    "            d *= 2\n",
    "    return d\n",
    "\n",
    "def _attack_ceiling(pk):\n",
    "    \"\"\"Return highest-damage attack this Pokémon has.\"\"\"\n",
    "    C, A = _meta()\n",
    "    if not pk:\n",
    "        return 0\n",
    "    c = C.get(pk.get(\"id\"))\n",
    "    if not c:\n",
    "        return 0\n",
    "    dmgs = []\n",
    "    for aid in getattr(c, 'attacks', []):\n",
    "        if aid in A:\n",
    "            for dmg, _ in A[aid]:\n",
    "                dmgs.append(dmg)\n",
    "    return max(dmgs) if dmgs else 0\n",
    "\n",
    "_state = {\"turn\": None, \"actions\": 0}\n",
    "\n",
    "def _clamp(indices, sel):\n",
    "    \"\"\"Clamp indices to selection bounds.\"\"\"\n",
    "    mn, mx, n = sel[\"minCount\"], sel[\"maxCount\"], len(sel[\"option\"])\n",
    "    out = []\n",
    "    for i in indices:\n",
    "        if 0 <= i < n and i not in out:\n",
    "            out.append(i)\n",
    "        if len(out) >= mx:\n",
    "            break\n",
    "    i = 0\n",
    "    while len(out) < mn and i < n:\n",
    "        if i not in out:\n",
    "            out.append(i)\n",
    "        i += 1\n",
    "    return out\n",
    "\n",
    "def _quick_policy(obs_dict, deck):\n",
    "    \"\"\"Fast fallback rule policy.\"\"\"\n",
    "    sel = obs_dict.get(\"select\")\n",
    "    if sel is None:\n",
    "        return deck\n",
    "    opts = sel[\"option\"]\n",
    "    n = len(opts)\n",
    "    if n == 0:\n",
    "        return []\n",
    "    \n",
    "    mn, mx = sel[\"minCount\"], sel[\"maxCount\"]\n",
    "    stype = sel[\"type\"]\n",
    "    cur = obs_dict.get(\"current\") or {}\n",
    "    t = cur.get(\"turn\")\n",
    "    \n",
    "    if t != _state[\"turn\"]:\n",
    "        _state[\"turn\"] = t\n",
    "        _state[\"actions\"] = 0\n",
    "    _state[\"actions\"] += 1\n",
    "    panic = _state[\"actions\"] > ACTIONS_PER_TURN_CAP\n",
    "    \n",
    "    if stype == 0:\n",
    "        me = cur.get(\"yourIndex\", 0)\n",
    "        players = cur.get(\"players\", [])\n",
    "        active = (players[me][\"active\"][0] if players and players[me].get(\"active\") else None)\n",
    "        opp = players[1 - me] if players and len(players) == 2 else None\n",
    "        oa = opp[\"active\"][0] if opp and opp.get(\"active\") else None\n",
    "        opp_hp = oa.get(\"hp\", 9999) if oa else 9999\n",
    "        ba = _affordable_dmg(active)\n",
    "        bm = _attack_ceiling(active)\n",
    "        has_attach = any(o.get(\"type\") == ATTACH for o in opts)\n",
    "        can_ko = ba > 0 and ba >= opp_hp\n",
    "        \n",
    "        if CHARGE_TO_BEST:\n",
    "            ready = can_ko or (ba >= STRONG_ATTACK and (ba >= bm or not has_attach))\n",
    "        else:\n",
    "            ready = ba >= STRONG_ATTACK or can_ko\n",
    "        \n",
    "        PRI = {ABILITY: 6, EVOLVE: 5, PLAY: 4, ATTACH: 3, SKILL: 4, END: 1, RETREAT: 0, DISCARD: 0}\n",
    "        bi, bs = 0, -1e9\n",
    "        for i, o in enumerate(opts):\n",
    "            ot = o.get(\"type\")\n",
    "            if ot == ATTACK:\n",
    "                s = 7 if ready else 1.5\n",
    "            else:\n",
    "                s = PRI.get(ot, 2)\n",
    "                if ot == ATTACH and o.get(\"inPlayArea\") == 4:\n",
    "                    s += 0.5\n",
    "            if s > bs:\n",
    "                bs, bi = s, i\n",
    "        \n",
    "        if panic:\n",
    "            for i, o in enumerate(opts):\n",
    "                if o.get(\"type\") == ATTACK:\n",
    "                    return [i]\n",
    "            for i, o in enumerate(opts):\n",
    "                if o.get(\"type\") == END:\n",
    "                    return [i]\n",
    "        \n",
    "        return [bi]\n",
    "    \n",
    "    if stype == 6:\n",
    "        _, A = _meta()\n",
    "        return [max(range(n), key=lambda i: max((x[0] for x in A.get(opts[i].get(\"attackId\"), [(0, ())])), default=0))]\n",
    "    if stype == 8:\n",
    "        return [max(range(n), key=lambda i: opts[i].get(\"number\", 0) or 0)]\n",
    "    if stype == 9:\n",
    "        for i, o in enumerate(opts):\n",
    "            if o.get(\"type\") == YES:\n",
    "                return [i]\n",
    "        return [0]\n",
    "    if stype == 4:\n",
    "        return _clamp(list(range(n)), sel)\n",
    "    \n",
    "    k = mn if mn > 0 else (1 if mx >= 1 else 0)\n",
    "    return _clamp(list(range(n))[:k] if k else [], sel)\n",
    "\n",
    "def _active(p):\n",
    "    \"\"\"Get active Pokémon from PlayerState.\"\"\"\n",
    "    a = p.get(\"active\")\n",
    "    return a[0] if a and len(a) > 0 and a[0] else None\n",
    "\n",
    "def _hp_tot(p):\n",
    "    \"\"\"Sum total current HP.\"\"\"\n",
    "    return sum(\n",
    "        (x.get(\"hp\", 0) or 0)\n",
    "        for x in (p.get(\"active\") or []) + (p.get(\"bench\") or [])\n",
    "        if x\n",
    "    )\n",
    "\n",
    "def evaluate(state, me):\n",
    "    \"\"\"Evaluate board state. Higher = better FOR YOU.\"\"\"\n",
    "    if state is None:\n",
    "        return 0.0\n",
    "    \n",
    "    P = state.get(\"players\", [])\n",
    "    if len(P) < 2:\n",
    "        return 0.0\n",
    "    \n",
    "    mp = P[me]\n",
    "    op = P[1 - me]\n",
    "    res = state.get(\"result\", -1)\n",
    "    \n",
    "    if res == me:\n",
    "        return BIG\n",
    "    if res != -1:\n",
    "        return -BIG\n",
    "    \n",
    "    mypz = len(mp.get(\"prize\") or [])\n",
    "    oppz = len(op.get(\"prize\") or [])\n",
    "    \n",
    "    if mypz == 0:\n",
    "        return BIG\n",
    "    if oppz == 0:\n",
    "        return -BIG\n",
    "    \n",
    "    ma = _active(mp)\n",
    "    oa = _active(op)\n",
    "    mb = [x for x in (mp.get(\"bench\") or []) if x]\n",
    "    ob = [x for x in (op.get(\"bench\") or []) if x]\n",
    "    \n",
    "    if oa is None and not ob:\n",
    "        return BIG\n",
    "    if ma is None and not mb:\n",
    "        return -BIG\n",
    "    \n",
    "    s = W_PRIZE * (oppz - mypz)\n",
    "    s -= 0.20 * _hp_tot(op)\n",
    "    s += 0.10 * _hp_tot(mp)\n",
    "    \n",
    "    if ma and oa:\n",
    "        oah = oa.get(\"hp\", 0) or 0\n",
    "        mah = ma.get(\"hp\", 0) or 0\n",
    "        my_dmg = _damage_to(ma, oa)\n",
    "        opp_dmg = _damage_to(oa, ma)\n",
    "        \n",
    "        if oah > 0 and my_dmg >= oah:\n",
    "            s += W_KO_THEM * _prize_value(oa.get(\"id\"))\n",
    "        \n",
    "        if mah > 0 and opp_dmg >= mah:\n",
    "            ex_mult = 1.4 if _is_ex(ma.get(\"id\")) else 1.0\n",
    "            s -= W_KO_ME * ex_mult * _prize_value(ma.get(\"id\"))\n",
    "        \n",
    "        if mah > 0 and opp_dmg < mah:\n",
    "            buffer = mah - opp_dmg\n",
    "            surv_score = W_SURVIVE * min(1.0, (buffer ** 0.5) / 16.0)\n",
    "            s += surv_score\n",
    "    \n",
    "    if ma and _affordable_dmg(ma) > 0:\n",
    "        s += W_ACTIVE_READY\n",
    "    \n",
    "    backup_count = 0\n",
    "    for pk in mb:\n",
    "        if pk.get(\"id\") in [333, 678, 135]:\n",
    "            if _affordable_dmg(pk) > 0:\n",
    "                backup_count += 1\n",
    "    s += W_BACKUP * min(2, backup_count)\n",
    "    \n",
    "    unneeded_ex = max(0, sum(1 for x in mb if _is_ex(x.get(\"id\"))) - 1)\n",
    "    s -= W_BENCH_EXPOSURE * unneeded_ex\n",
    "    \n",
    "    ma_locked = ma and (\n",
    "        ma.get(\"asleep\") or ma.get(\"paralyzed\") or ma.get(\"confused\")\n",
    "    )\n",
    "    oa_locked = oa and (\n",
    "        oa.get(\"asleep\") or oa.get(\"paralyzed\") or oa.get(\"confused\")\n",
    "    )\n",
    "    \n",
    "    if ma_locked:\n",
    "        s -= W_CONDITIONS_SELF\n",
    "    if oa_locked:\n",
    "        s += W_CONDITIONS_OPP\n",
    "    \n",
    "    hc = mp.get(\"handCount\", 0) or 0\n",
    "    s += W_HAND * (min(hc, 8) - 3)\n",
    "    \n",
    "    my_deck = mp.get(\"deckCount\", 0) or 0\n",
    "    opp_deck = op.get(\"deckCount\", 0) or 0\n",
    "    if min(my_deck, opp_deck) <= 6:\n",
    "        s += W_DECKOUT * (my_deck - opp_deck)\n",
    "    \n",
    "    return s\n",
    "\n",
    "def _vis(state, me):\n",
    "    \"\"\"Return visible card ids for player `me`.\"\"\"\n",
    "    seen = []\n",
    "    p = state.get(\"players\", [{}])[me]\n",
    "    for c in (p.get(\"hand\") or []):\n",
    "        seen.append(c.get(\"id\"))\n",
    "    for c in (p.get(\"discard\") or []):\n",
    "        seen.append(c.get(\"id\"))\n",
    "    \n",
    "    def add(pk):\n",
    "        if not pk:\n",
    "            return\n",
    "        seen.append(pk.get(\"id\"))\n",
    "        for e in (pk.get(\"energyCards\") or []):\n",
    "            seen.append(e.get(\"id\"))\n",
    "        for tl in (pk.get(\"tools\") or []):\n",
    "            seen.append(tl.get(\"id\"))\n",
    "        for pe in (pk.get(\"preEvolution\") or []):\n",
    "            seen.append(pe.get(\"id\"))\n",
    "    \n",
    "    for pk in (p.get(\"active\") or []):\n",
    "        add(pk)\n",
    "    for pk in (p.get(\"bench\") or []):\n",
    "        add(pk)\n",
    "    \n",
    "    return seen\n",
    "\n",
    "def _determinize(obs, my_deck):\n",
    "    \"\"\"Determinize hidden information for search.\"\"\"\n",
    "    state = obs.get(\"current\", {})\n",
    "    me = state.get(\"yourIndex\", 0)\n",
    "    opp = 1 - me\n",
    "    mp = state.get(\"players\", [{}])[me]\n",
    "    op = state.get(\"players\", [{}])[opp]\n",
    "    \n",
    "    rem = list((Counter(my_deck) - Counter(_vis(state, me))).elements())\n",
    "    random.shuffle(rem)\n",
    "    nd = mp.get(\"deckCount\", 0)\n",
    "    npz = len(mp.get(\"prize\", []))\n",
    "    while len(rem) < nd + npz:\n",
    "        rem.append(my_deck[0])\n",
    "    yd = rem[:nd]\n",
    "    yp = rem[nd:nd + npz]\n",
    "    \n",
    "    pool = list(my_deck) * 3\n",
    "    random.shuffle(pool)\n",
    "    od = pool[:op.get(\"deckCount\", 0)]\n",
    "    opz = pool[:len(op.get(\"prize\", []))]\n",
    "    oh = pool[:op.get(\"handCount\", 0)]\n",
    "    oa = [678] if (op.get(\"active\") and op[\"active\"] and op[\"active\"][0] is None) else []\n",
    "    \n",
    "    return yd, yp, od, opz, oh, oa\n",
    "\n",
    "def _d(x):\n",
    "    \"\"\"Convert dataclass to dict.\"\"\"\n",
    "    return dataclasses.asdict(x) if (x is not None and dataclasses.is_dataclass(x)) else x\n",
    "\n",
    "def _rollout(child, me, deck, max_steps=64):\n",
    "    \"\"\"Rollout from child state: finish YOUR turn, evaluate leaf.\"\"\"\n",
    "    try:\n",
    "        from cg.api import search_step\n",
    "    except Exception:\n",
    "        return evaluate(_d(child.observation.current) if hasattr(child, 'observation') else None, me)\n",
    "    \n",
    "    so = child.observation\n",
    "    steps = 0\n",
    "    \n",
    "    while steps < max_steps:\n",
    "        cur = _d(so.current)\n",
    "        sel = so.select\n",
    "        \n",
    "        if cur is not None and cur.get(\"result\", -1) != -1:\n",
    "            return BIG if cur[\"result\"] == me else -BIG\n",
    "        \n",
    "        if sel is None:\n",
    "            break\n",
    "        \n",
    "        if cur is not None and cur.get(\"yourIndex\", me) != me:\n",
    "            break\n",
    "        \n",
    "        try:\n",
    "            child = search_step(child.searchId, _quick_policy(_d(so), deck))\n",
    "        except Exception:\n",
    "            break\n",
    "        \n",
    "        so = child.observation\n",
    "        steps += 1\n",
    "    \n",
    "    return evaluate(_d(so.current), me)\n",
    "\n",
    "def _search_choose(obs_dict, deck):\n",
    "    \"\"\"Determinized forward search on MAIN decisions.\"\"\"\n",
    "    sel = obs_dict.get(\"select\")\n",
    "    if sel is None:\n",
    "        return deck\n",
    "    \n",
    "    if sel.get(\"type\") != 0 or len(sel.get(\"option\", [])) < 2:\n",
    "        return _quick_policy(obs_dict, deck)\n",
    "    \n",
    "    try:\n",
    "        from cg.api import to_observation_class, search_begin, search_step, search_end\n",
    "        \n",
    "        o = to_observation_class(obs_dict)\n",
    "        yd, yp, od, op, oh, oa = _determinize(obs_dict, deck)\n",
    "        root = search_begin(o, yd, yp, od, op, oh, oa, manual_coin=False)\n",
    "        me = obs_dict[\"current\"][\"yourIndex\"]\n",
    "        best_i, best_v = 0, -1e18\n",
    "        \n",
    "        for i in range(len(sel[\"option\"])):\n",
    "            try:\n",
    "                child = search_step(root.searchId, [i])\n",
    "            except Exception:\n",
    "                continue\n",
    "            \n",
    "            v = _rollout(child, me, deck)\n",
    "            if v > best_v:\n",
    "                best_v, best_i = v, i\n",
    "        \n",
    "        search_end()\n",
    "        return [best_i]\n",
    "    \n",
    "    except Exception:\n",
    "        return _quick_policy(obs_dict, deck)\n",
    "\n",
    "def agent(obs_dict):\n",
    "    \"\"\"Main agent entry point.\"\"\"\n",
    "    return _search_choose(obs_dict, DECK)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.13"
  },
  "papermill": {
   "default_parameters": {},
   "duration": 18.354655,
   "end_time": "2026-06-20T19:22:21.522317+00:00",
   "environment_variables": {},
   "exception": null,
   "input_path": "__notebook__.ipynb",
   "output_path": "__notebook__.ipynb",
   "parameters": {},
   "start_time": "2026-06-20T19:22:03.167662+00:00",
   "version": "2.7.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
